SRCS	= ft_atoi.c \
		  ft_isalnum.c \
		  ft_isalpha.c \
		  ft_isascii.c \
		  ft_isdigit.c \
		  ft_isprint.c \
		  ft_strlcat.c \
		  ft_strlen.c \
		  ft_strncmp.c \
		  ft_tolower.c \
		  ft_toupper.c \
		  ft_strnstr.c \
		  ft_strchr.c \
		  ft_strrchr.c \
		  ft_strdup.c \
		  ft_strlcpy.c \
		  ft_bzero.c \
		  ft_memcpy.c \
		  ft_memset.c \
		  ft_memchr.c \
		  ft_memcmp.c \
		  ft_memmove.c \
		  ft_calloc.c \
		  ft_substr.c \
		  ft_itoa.c \
		  ft_strjoin.c \
		  ft_putchar_fd.c \
		  ft_putstr_fd.c \
		  ft_putendl_fd.c \
		  ft_putnbr_fd.c \
		  ft_split.c \
		  ft_strmapi.c \
		  ft_strtrim.c \
		  ft_striteri.c \

SRCLST	= ft_lstadd_back_bonus.c \
		  ft_lstadd_front_bonus.c \
		  ft_lstclear_bonus.c \
		  ft_lstdelone_bonus.c \
		  ft_lstiter_bonus.c \
		  ft_lstlast_bonus.c \
		  ft_lstmap_bonus.c \
		  ft_lstnew_bonus.c \
		  ft_lstsize_bonus.c

OBJS	= ${SRCS:.c=.o}

OBJSLST	= ${SRCLST:.c=.o}

CC	= cc

CFLAGS	= -Wall -Werror -Wextra

AR	= ar rc

NAME	= libft.a

RM	= rm -f

.c.o:
		${CC} ${CFLAGS} -c $< -o ${<:.c=.o}

${NAME}:	${OBJS}
		@${AR} ${NAME} ${OBJS}

bonus:		${OBJS} ${OBJSLST}
		@${AR} ${NAME} ${OBJS} ${OBJSLST}

clean:
		@${RM} ${OBJS} ${OBJSLST}

fclean:		clean
		@${RM} ${NAME}

all:		${NAME}

re:		fclean all

.PHONY:		all clean fclean re
